#Xpfly配置文件 Authorized by Xiaye_
#插件版本,请勿修改
version: 1.0
#未开启飞行时,当玩家经验值不足,无法开启飞行时的提示语句
#如需使用彩色代码,应当使用§
fail_to_enable_fly: '条件不满足,无法开启飞行'
#开启飞行后,玩家经验值耗尽,飞行被关闭时的提示语句
out_of_exp: '经验不足,无法继续飞行'
#飞行的价格.单位经验值
price: 5
#每隔多少秒扣除一次经验
timer: 1